### ISSUE TITLE
Possible to do union between "Paths"?

### ISSUE THREAD

**Issue by AndrewHartAR** [lhuanyu/SwiftClipper#1]
I have two Paths - `previousPaths` and `currentPaths`, and I wish to find the intersections between them, as a single Paths. My thought here is that I could potentially find the intersections between `currentPaths` and each individual Path in `previousPaths`, which gets me an array of Paths. Now, I wish to unionise them. Perhaps I'm taking the wrong approach, but it's unclear to me how to do this.

Does there needed to be a function added for `union(path: Path)`?

```
var intersections = [Paths]()

for path in previousPaths {
	let intersection = currentPaths.intersection(path)
	intersections.append(intersection)
}
```

**Comment by lhuanyu** [comment]
There is actually a function for Paths union. I guess you want to do the following calculation?
```
extension Paths {
    public func unions(_ isClosed: Bool = true) -> Paths {
        var paths = Paths()
        let c = Clipper()
        c.addPaths(self, .subject, isClosed)
        _ = try? c.execute(clipType: .union, solution: &paths)
        return paths
    }
}
```

**Comment by AndrewHartAR** [comment]
That looks great, thanks for clarifying.
